version: 2.0.0-{build}
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - dev
    - /^release\/.*/
skip_non_tags: true
build_script:
  - ps: .\build.ps1
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    IsFinalBuild: true
test: off
deploy: off
artifacts:
  - path: 'artifacts\build\*.nupkg'
os: Visual Studio 2017
