version: 3.0.0-{build}
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - dev
    - /^release\/.*/
build_script:
  - eng\common\CIBuild.cmd -configuration Release -prepareMachine
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
deploy: off
artifacts:
  - path: artifacts\packages\Release\Shipping\*.nupkg
os: Visual Studio 2019
