version: 3.0.0-{build}
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - dev
    - /^release\/.*/
build_script:
  - ps: .\run.ps1 default-build
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
deploy: off
artifacts:
  - path: 'artifacts\build\*.nupkg'
os: Visual Studio 2019 Preview
