language: csharp
mono: none
sudo: false
dist: xenial
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - NUGET_XMLDOC_MODE: skip
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8
branches:
  only:
    - master
    - dev
    - /^release\/.*/
script:
  - ./eng/common/cibuild.sh --configuration Release --prepareMachine
